name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
name = "formal_conjectures"
path = "../"

[[require]]
name = "verso"
git = "https://github.com/mo271/verso.git"
rev = "bd3376ad6d048ddad473fb573631aa641158ff74"
