name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
name = "formal_conjectures"
path = "../"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso.git"
rev = "v4.27.0"
