/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# Distance certificates for the truncated-octahedron dissection

Machine-generated Positivstellensatz certificates (branch-and-certify: recursive
midpoint case splits with a degree-2 Handelman certificate at every leaf, found by
linear programming) proving that each piece of the dissection of the truncated
octahedron `{‖x‖₁ ≤ 3 / 2, xⱼ ≤ 13 / 15}` — the cap `A` (`x₀+x₁+x₂ ≥ 5 / 12`, all
`xⱼ ≥ -7 / 24`) and, for each sector, the two convex cells `C1` (`x₀` minimal, sum
`≤ 5 / 12`) and `C2` (`x₀` minimal, `x₀ ≤ -7 / 24`) — has squared diameter at most
`149 / 50 < 3`.  The exact maxima are `21121 / 7200` for `A` and `7057 / 2400` for the
sectors, so the bound has margin.  The hypotheses take the eight sign patterns of the
`ℓ¹` bound and the remaining facets in explicit `0 ≤ ⋯` form.

Generated by `certgen.py`; see `docs/dimension-3-4-program.md`.
-/

namespace Borsuk

-- the certificate lemmas share a uniform machine-generated hypothesis interface, in
-- which individual facet hypotheses may go unused by a particular certificate
set_option linter.unusedVariables false

namespace Space.Cert

set_option maxHeartbeats 1600000 in
-- the branch-and-certify case tree is large
@[category API, AMS 52]
theorem certAA (x0 x1 x2 y0 y1 y2 : ℝ)
    (hx0 : (0 : ℝ) ≤ 3 / 2 - (x0 + x1 + x2)) (hx1 : (0 : ℝ) ≤ 3 / 2 - (x0 + x1 - x2))
    (hx2 : (0 : ℝ) ≤ 3 / 2 - (x0 - x1 + x2)) (hx3 : (0 : ℝ) ≤ 3 / 2 - (x0 - x1 - x2))
    (hx4 : (0 : ℝ) ≤ 3 / 2 - (-x0 + x1 + x2)) (hx5 : (0 : ℝ) ≤ 3 / 2 - (-x0 + x1 - x2))
    (hx6 : (0 : ℝ) ≤ 3 / 2 - (-x0 - x1 + x2)) (hx7 : (0 : ℝ) ≤ 3 / 2 - (-x0 - x1 - x2))
    (hx8 : (0 : ℝ) ≤ 13 / 15 - x0) (hx9 : (0 : ℝ) ≤ 13 / 15 - x1)
    (hx10 : (0 : ℝ) ≤ 13 / 15 - x2) (hx11 : (0 : ℝ) ≤ x0 + x1 + x2 - 5 / 12)
    (hx12 : (0 : ℝ) ≤ x0 + 7 / 24) (hx13 : (0 : ℝ) ≤ x1 + 7 / 24)
    (hx14 : (0 : ℝ) ≤ x2 + 7 / 24) (hy0 : (0 : ℝ) ≤ 3 / 2 - (y0 + y1 + y2))
    (hy1 : (0 : ℝ) ≤ 3 / 2 - (y0 + y1 - y2)) (hy2 : (0 : ℝ) ≤ 3 / 2 - (y0 - y1 + y2))
    (hy3 : (0 : ℝ) ≤ 3 / 2 - (y0 - y1 - y2)) (hy4 : (0 : ℝ) ≤ 3 / 2 - (-y0 + y1 + y2))
    (hy5 : (0 : ℝ) ≤ 3 / 2 - (-y0 + y1 - y2)) (hy6 : (0 : ℝ) ≤ 3 / 2 - (-y0 - y1 + y2))
    (hy7 : (0 : ℝ) ≤ 3 / 2 - (-y0 - y1 - y2)) (hy8 : (0 : ℝ) ≤ 13 / 15 - y0)
    (hy9 : (0 : ℝ) ≤ 13 / 15 - y1) (hy10 : (0 : ℝ) ≤ 13 / 15 - y2)
    (hy11 : (0 : ℝ) ≤ y0 + y1 + y2 - 5 / 12) (hy12 : (0 : ℝ) ≤ y0 + 7 / 24)
    (hy13 : (0 : ℝ) ≤ y1 + 7 / 24) (hy14 : (0 : ℝ) ≤ y2 + 7 / 24)
    :
    (x0 - y0) ^ 2 + (x1 - y1) ^ 2 + (x2 - y2) ^ 2 ≤ 149 / 50 := by
  rcases le_total y1 (1 / 2 : ℝ) with hbr0 | hbr0
  · have hbr0n : (0 : ℝ) ≤ 1 / 2 - y1 := by linarith
    rcases le_total y2 (1 / 2 : ℝ) with hbr1 | hbr1
    · have hbr1n : (0 : ℝ) ≤ 1 / 2 - y2 := by linarith
      rcases le_total x2 (1 / 2 : ℝ) with hbr2 | hbr2
      · have hbr2n : (0 : ℝ) ≤ 1 / 2 - x2 := by linarith
        rcases le_total x0 (1 / 2 : ℝ) with hbr3 | hbr3
        · have hbr3n : (0 : ℝ) ≤ 1 / 2 - x0 := by linarith
          rcases le_total y2 (0 : ℝ) with hbr4 | hbr4
          · have hbr4n : (0 : ℝ) ≤ 0 - y2 := by linarith
            linarith [mul_nonneg hx0 hx12, mul_nonneg hx4 hx11, mul_nonneg hx4 hbr0n,
              mul_nonneg hx4 hbr3n, mul_nonneg hx4 hbr4n, mul_nonneg hx9 hy14,
              mul_nonneg hx9 hbr0n, mul_nonneg hx9 hbr2n, mul_nonneg hx11 hy8,
              mul_nonneg hx11 hy11, mul_nonneg hx12 hy11, mul_nonneg hx12 hbr3n,
              mul_nonneg hy0 hy11, mul_nonneg hy2 hy11, mul_nonneg hy8 hy11, mul_nonneg hy8 hbr0n,
              mul_nonneg hy8 hbr3n, mul_nonneg hy8 hbr4n, mul_nonneg hy11 hbr4n,
              mul_nonneg hy13 hy14, mul_nonneg hy13 hbr0n, mul_nonneg hy13 hbr2n,
              mul_nonneg hy13 hbr3n, mul_nonneg hbr2n hbr4n]
          · have hbr4n : (0 : ℝ) ≤ y2 - (0) := by linarith
            rcases le_total y1 (0 : ℝ) with hbr5 | hbr5
            · have hbr5n : (0 : ℝ) ≤ 0 - y1 := by linarith
              linarith [mul_nonneg hx1 hy8, mul_nonneg hx4 hx11, mul_nonneg hx4 hx14,
                mul_nonneg hx9 hx13, mul_nonneg hx9 hy11, mul_nonneg hx9 hbr2n,
                mul_nonneg hx9 hbr5n, mul_nonneg hx11 hy11, mul_nonneg hx11 hy13,
                mul_nonneg hx11 hbr2n, mul_nonneg hx11 hbr4n, mul_nonneg hx12 hx14,
                mul_nonneg hx12 hy11, mul_nonneg hx12 hbr1n, mul_nonneg hx12 hbr3n,
                mul_nonneg hx14 hy8, mul_nonneg hx14 hy13, mul_nonneg hy2 hy11,
                mul_nonneg hy2 hbr2n, mul_nonneg hy8 hbr1n, mul_nonneg hy8 hbr3n,
                mul_nonneg hy13 hbr3n, mul_nonneg hy13 hbr5n]
            · have hbr5n : (0 : ℝ) ≤ y1 - (0) := by linarith
              linarith [mul_nonneg hx9 hx13, mul_nonneg hx9 hy11, mul_nonneg hx9 hbr0n,
                mul_nonneg hx9 hbr2n, mul_nonneg hx9 hbr4n, mul_nonneg hx11 hy11,
                mul_nonneg hx11 hbr0n, mul_nonneg hx11 hbr2n, mul_nonneg hx11 hbr4n,
                mul_nonneg hx12 hx14, mul_nonneg hx12 hy12, mul_nonneg hx12 hbr1n,
                mul_nonneg hx12 hbr3n, mul_nonneg hx13 hbr5n, mul_nonneg hx14 hy8,
                mul_nonneg hx14 hbr2n, mul_nonneg hy8 hy12, mul_nonneg hy8 hbr3n,
                mul_nonneg hbr0n hbr5n, mul_nonneg hbr1n hbr2n, mul_nonneg hbr1n hbr4n,
                mul_nonneg hbr2n hbr5n, mul_nonneg hbr3n hbr5n]
        · have hbr3n : (0 : ℝ) ≤ x0 - (1 / 2) := by linarith
          linarith [mul_nonneg hx0 hx8, mul_nonneg hx0 hx11, mul_nonneg hx0 hy12,
            mul_nonneg hx0 hbr0n, mul_nonneg hx1 hx13, mul_nonneg hx1 hy14, mul_nonneg hx1 hbr0n,
            mul_nonneg hx8 hx9, mul_nonneg hx8 hy11, mul_nonneg hx8 hy13, mul_nonneg hx8 hbr3n,
            mul_nonneg hx9 hbr0n, mul_nonneg hx11 hy11, mul_nonneg hx13 hy13,
            mul_nonneg hx13 hbr1n, mul_nonneg hx14 hy11, mul_nonneg hx14 hy14,
            mul_nonneg hx14 hbr2n, mul_nonneg hy8 hy12, mul_nonneg hy12 hbr2n,
            mul_nonneg hy12 hbr3n, mul_nonneg hy13 hbr0n, mul_nonneg hy14 hbr1n,
            mul_nonneg hbr1n hbr2n]
      · have hbr2n : (0 : ℝ) ≤ x2 - (1 / 2) := by linarith
        rcases le_total y0 (1 / 2 : ℝ) with hbr6 | hbr6
        · have hbr6n : (0 : ℝ) ≤ 1 / 2 - y0 := by linarith
          linarith [mul_nonneg hx0 hx10, mul_nonneg hx0 hx11, mul_nonneg hx0 hy14,
            mul_nonneg hx2 hx12, mul_nonneg hx2 hbr6n, mul_nonneg hx4 hx13, mul_nonneg hx4 hbr0n,
            mul_nonneg hx8 hx12, mul_nonneg hx8 hbr6n, mul_nonneg hx9 hx13, mul_nonneg hx9 hbr0n,
            mul_nonneg hx10 hy11, mul_nonneg hx10 hbr1n, mul_nonneg hx10 hbr2n,
            mul_nonneg hx11 hy11, mul_nonneg hx12 hy12, mul_nonneg hx13 hy13,
            mul_nonneg hy12 hbr6n, mul_nonneg hy13 hbr0n, mul_nonneg hy14 hbr1n,
            mul_nonneg hy14 hbr2n]
        · have hbr6n : (0 : ℝ) ≤ y0 - (1 / 2) := by linarith
          rcases le_total y2 (0 : ℝ) with hbr7 | hbr7
          · have hbr7n : (0 : ℝ) ≤ 0 - y2 := by linarith
            rcases le_total y1 (0 : ℝ) with hbr8 | hbr8
            · have hbr8n : (0 : ℝ) ≤ 0 - y1 := by linarith
              linarith [mul_nonneg hx0 hx12, mul_nonneg hx0 hy14, mul_nonneg hx1 hx12,
                mul_nonneg hx4 hx13, mul_nonneg hx4 hy12, mul_nonneg hx4 hbr8n, mul_nonneg hx8 hy8,
                mul_nonneg hx9 hx10, mul_nonneg hx9 hy14, mul_nonneg hx10 hy13,
                mul_nonneg hx10 hbr2n, mul_nonneg hx10 hbr7n, mul_nonneg hx11 hy11,
                mul_nonneg hx12 hbr2n, mul_nonneg hx12 hbr6n, mul_nonneg hx12 hbr7n,
                mul_nonneg hx13 hy8, mul_nonneg hx14 hy8, mul_nonneg hy4 hy11, mul_nonneg hy8 hy12,
                mul_nonneg hy8 hbr8n, mul_nonneg hy11 hbr8n, mul_nonneg hy13 hy14,
                mul_nonneg hy14 hbr2n, mul_nonneg hy14 hbr7n]
            · have hbr8n : (0 : ℝ) ≤ y1 - (0) := by linarith
              rcases le_total x1 (1 / 2 : ℝ) with hbr9 | hbr9
              · have hbr9n : (0 : ℝ) ≤ 1 / 2 - x1 := by linarith
                linarith [mul_nonneg hx1 hx10, mul_nonneg hx2 hx12, mul_nonneg hx2 hy8,
                  mul_nonneg hx8 hx10, mul_nonneg hx8 hy8, mul_nonneg hx10 hbr2n,
                  mul_nonneg hx10 hbr6n, mul_nonneg hx10 hbr8n, mul_nonneg hx10 hbr9n,
                  mul_nonneg hx11 hbr8n, mul_nonneg hx11 hbr9n, mul_nonneg hx12 hbr0n,
                  mul_nonneg hx12 hbr6n, mul_nonneg hx13 hy8, mul_nonneg hx13 hy14,
                  mul_nonneg hy1 hbr8n, mul_nonneg hy1 hbr9n, mul_nonneg hy8 hbr0n,
                  mul_nonneg hy8 hbr6n, mul_nonneg hy14 hbr0n, mul_nonneg hy14 hbr2n,
                  mul_nonneg hy14 hbr7n]
              · have hbr9n : (0 : ℝ) ≤ x1 - (1 / 2) := by linarith
                linarith [mul_nonneg hx0 hy8, mul_nonneg hx0 hbr9n, mul_nonneg hx4 hx8,
                  mul_nonneg hx4 hy12, mul_nonneg hx4 hbr2n, mul_nonneg hx4 hbr6n,
                  mul_nonneg hx8 hy8, mul_nonneg hx10 hx12, mul_nonneg hx13 hbr8n,
                  mul_nonneg hx14 hy14, mul_nonneg hy8 hy12, mul_nonneg hy14 hbr1n,
                  mul_nonneg hy14 hbr2n, mul_nonneg hbr0n hbr8n, mul_nonneg hbr2n hbr9n,
                  mul_nonneg hbr8n hbr9n]
          · have hbr7n : (0 : ℝ) ≤ y2 - (0) := by linarith
            linarith [mul_nonneg hx0 hx12, mul_nonneg hx0 hy8, mul_nonneg hx4 hx13,
              mul_nonneg hx4 hbr0n, mul_nonneg hx4 hbr6n, mul_nonneg hx8 hy8, mul_nonneg hx8 hbr7n,
              mul_nonneg hx9 hx10, mul_nonneg hx9 hbr0n, mul_nonneg hx10 hy13,
              mul_nonneg hx10 hbr2n, mul_nonneg hx11 hy13, mul_nonneg hx11 hbr2n,
              mul_nonneg hx12 hy11, mul_nonneg hx12 hbr2n, mul_nonneg hx13 hy13,
              mul_nonneg hx14 hbr7n, mul_nonneg hy8 hbr6n, mul_nonneg hy13 hbr0n,
              mul_nonneg hbr1n hbr7n, mul_nonneg hbr2n hbr7n]
    · have hbr1n : (0 : ℝ) ≤ y2 - (1 / 2) := by linarith
      rcases le_total x1 (1 / 2 : ℝ) with hbr10 | hbr10
      · have hbr10n : (0 : ℝ) ≤ 1 / 2 - x1 := by linarith
        rcases le_total x0 (1 / 2 : ℝ) with hbr11 | hbr11
        · have hbr11n : (0 : ℝ) ≤ 1 / 2 - x0 := by linarith
          linarith [mul_nonneg hx10 hx14, mul_nonneg hx11 hy10, mul_nonneg hx11 hy11,
            mul_nonneg hx11 hy13, mul_nonneg hx12 hy10, mul_nonneg hx12 hy12,
            mul_nonneg hx12 hbr11n, mul_nonneg hx13 hy2, mul_nonneg hx13 hy13,
            mul_nonneg hx13 hbr10n, mul_nonneg hx14 hy0, mul_nonneg hx14 hbr0n,
            mul_nonneg hx14 hbr1n, mul_nonneg hy0 hy10, mul_nonneg hy0 hy11, mul_nonneg hy0 hbr11n,
            mul_nonneg hy2 hy12, mul_nonneg hy2 hbr11n, mul_nonneg hy8 hy10, mul_nonneg hy8 hbr11n,
            mul_nonneg hy10 hbr1n, mul_nonneg hy12 hbr10n, mul_nonneg hy13 hbr0n,
            mul_nonneg hbr0n hbr10n]
        · have hbr11n : (0 : ℝ) ≤ x0 - (1 / 2) := by linarith
          rcases le_total y1 (0 : ℝ) with hbr12 | hbr12
          · have hbr12n : (0 : ℝ) ≤ 0 - y1 := by linarith
            linarith [mul_nonneg hx0 hx14, mul_nonneg hx1 hx13, mul_nonneg hx1 hbr1n,
              mul_nonneg hx1 hbr12n, mul_nonneg hx4 hx8, mul_nonneg hx8 hy2, mul_nonneg hx8 hbr10n,
              mul_nonneg hx8 hbr11n, mul_nonneg hx10 hy10, mul_nonneg hx13 hy10,
              mul_nonneg hx13 hy11, mul_nonneg hx14 hy13, mul_nonneg hx14 hbr1n,
              mul_nonneg hx14 hbr11n, mul_nonneg hy1 hy10, mul_nonneg hy2 hy12,
              mul_nonneg hy8 hy11, mul_nonneg hy10 hbr1n, mul_nonneg hy10 hbr11n,
              mul_nonneg hy11 hbr1n, mul_nonneg hy11 hbr12n, mul_nonneg hy12 hy13,
              mul_nonneg hy12 hbr10n, mul_nonneg hy12 hbr11n]
          · have hbr12n : (0 : ℝ) ≤ y1 - (0) := by linarith
            linarith [mul_nonneg hx0 hx8, mul_nonneg hx1 hbr0n, mul_nonneg hx2 hx14,
              mul_nonneg hx2 hy10, mul_nonneg hx8 hy8, mul_nonneg hx8 hbr1n, mul_nonneg hx8 hbr11n,
              mul_nonneg hx8 hbr12n, mul_nonneg hx11 hbr10n, mul_nonneg hx11 hbr12n,
              mul_nonneg hx13 hy12, mul_nonneg hx13 hbr12n, mul_nonneg hx14 hbr0n,
              mul_nonneg hx14 hbr1n, mul_nonneg hy0 hy10, mul_nonneg hy0 hy12,
              mul_nonneg hy4 hbr10n, mul_nonneg hy4 hbr11n, mul_nonneg hy4 hbr12n,
              mul_nonneg hy10 hbr0n, mul_nonneg hy10 hbr1n, mul_nonneg hy12 hbr1n,
              mul_nonneg hy12 hbr11n]
      · have hbr10n : (0 : ℝ) ≤ x1 - (1 / 2) := by linarith
        rcases le_total x0 (1 / 2 : ℝ) with hbr13 | hbr13
        · have hbr13n : (0 : ℝ) ≤ 1 / 2 - x0 := by linarith
          rcases le_total y1 (0 : ℝ) with hbr14 | hbr14
          · have hbr14n : (0 : ℝ) ≤ 0 - y1 := by linarith
            rcases le_total x0 (0 : ℝ) with hbr15 | hbr15
            · have hbr15n : (0 : ℝ) ≤ 0 - x0 := by linarith
              linarith [mul_nonneg hx4 hx14, mul_nonneg hx4 hy13, mul_nonneg hx9 hx13,
                mul_nonneg hx9 hy5, mul_nonneg hx9 hy14, mul_nonneg hx9 hbr14n,
                mul_nonneg hx10 hx11, mul_nonneg hx11 hy11, mul_nonneg hx11 hbr1n,
                mul_nonneg hx11 hbr10n, mul_nonneg hx11 hbr15n, mul_nonneg hx12 hx14,
                mul_nonneg hx12 hy10, mul_nonneg hx12 hy13, mul_nonneg hx14 hy8,
                mul_nonneg hx14 hbr1n, mul_nonneg hy0 hy13, mul_nonneg hy1 hy13,
                mul_nonneg hy2 hy11, mul_nonneg hy2 hy12, mul_nonneg hy2 hy14,
                mul_nonneg hy2 hbr15n, mul_nonneg hy8 hy10, mul_nonneg hy10 hy14,
                mul_nonneg hy10 hbr1n, mul_nonneg hy13 hbr14n]
            · have hbr15n : (0 : ℝ) ≤ x0 - (0) := by linarith
              linarith [mul_nonneg hx0 hx14, mul_nonneg hx1 hy1, mul_nonneg hx1 hy8,
                mul_nonneg hx1 hbr15n, mul_nonneg hx2 hy13, mul_nonneg hx4 hy10,
                mul_nonneg hx9 hx13, mul_nonneg hx9 hy12, mul_nonneg hx9 hbr10n,
                mul_nonneg hx9 hbr13n, mul_nonneg hx9 hbr14n, mul_nonneg hx10 hx14,
                mul_nonneg hx10 hy10, mul_nonneg hx14 hy11, mul_nonneg hx14 hbr1n,
                mul_nonneg hx14 hbr10n, mul_nonneg hx14 hbr13n, mul_nonneg hx14 hbr14n,
                mul_nonneg hy2 hy11, mul_nonneg hy8 hy10, mul_nonneg hy10 hbr15n,
                mul_nonneg hy11 hbr15n, mul_nonneg hy13 hbr13n, mul_nonneg hy13 hbr14n]
          · have hbr14n : (0 : ℝ) ≤ y1 - (0) := by linarith
            linarith [mul_nonneg hx0 hx9, mul_nonneg hx0 hx11, mul_nonneg hx1 hx12,
              mul_nonneg hx1 hy8, mul_nonneg hx4 hx14, mul_nonneg hx9 hy12, mul_nonneg hx9 hbr10n,
              mul_nonneg hx11 hy12, mul_nonneg hx11 hbr13n, mul_nonneg hx12 hy10,
              mul_nonneg hx12 hy12, mul_nonneg hx13 hbr14n, mul_nonneg hx14 hy8,
              mul_nonneg hx14 hbr1n, mul_nonneg hy0 hy11, mul_nonneg hy0 hbr13n,
              mul_nonneg hy2 hy12, mul_nonneg hy2 hbr13n, mul_nonneg hy8 hy10,
              mul_nonneg hy10 hbr1n, mul_nonneg hy12 hbr14n, mul_nonneg hbr0n hbr14n,
              mul_nonneg hbr1n hbr14n, mul_nonneg hbr10n hbr14n]
        · have hbr13n : (0 : ℝ) ≤ x0 - (1 / 2) := by linarith
          linarith [mul_nonneg hx0 hx14, mul_nonneg hx0 hy10, mul_nonneg hx1 hx6,
            mul_nonneg hx1 hx10, mul_nonneg hx1 hy14, mul_nonneg hx1 hbr10n, mul_nonneg hx1 hbr13n,
            mul_nonneg hx8 hbr13n, mul_nonneg hx9 hbr10n, mul_nonneg hy0 hy10, mul_nonneg hy0 hy11,
            mul_nonneg hy1 hy10, mul_nonneg hy10 hbr1n, mul_nonneg hy11 hbr1n,
            mul_nonneg hy12 hy13, mul_nonneg hy12 hbr13n, mul_nonneg hy13 hbr10n,
            mul_nonneg hbr10n hbr13n]
  · have hbr0n : (0 : ℝ) ≤ y1 - (1 / 2) := by linarith
    rcases le_total x2 (1 / 2 : ℝ) with hbr16 | hbr16
    · have hbr16n : (0 : ℝ) ≤ 1 / 2 - x2 := by linarith
      rcases le_total y0 (1 / 2 : ℝ) with hbr17 | hbr17
      · have hbr17n : (0 : ℝ) ≤ 1 / 2 - y0 := by linarith
        rcases le_total x0 (1 / 2 : ℝ) with hbr18 | hbr18
        · have hbr18n : (0 : ℝ) ≤ 1 / 2 - x0 := by linarith
          linarith [mul_nonneg hx9 hx13, mul_nonneg hx11 hy9, mul_nonneg hx11 hy11,
            mul_nonneg hx11 hy12, mul_nonneg hx12 hy4, mul_nonneg hx12 hy12,
            mul_nonneg hx12 hbr18n, mul_nonneg hx13 hy0, mul_nonneg hx13 hbr0n,
            mul_nonneg hx13 hbr17n, mul_nonneg hx14 hy9, mul_nonneg hx14 hy14,
            mul_nonneg hx14 hbr16n, mul_nonneg hy0 hy9, mul_nonneg hy0 hy11, mul_nonneg hy0 hbr16n,
            mul_nonneg hy4 hy14, mul_nonneg hy4 hbr16n, mul_nonneg hy9 hy10, mul_nonneg hy9 hbr0n,
            mul_nonneg hy10 hbr16n, mul_nonneg hy12 hbr17n, mul_nonneg hy14 hbr18n,
            mul_nonneg hbr17n hbr18n]
        · have hbr18n : (0 : ℝ) ≤ x0 - (1 / 2) := by linarith
          rcases le_total y0 (0 : ℝ) with hbr19 | hbr19
          · have hbr19n : (0 : ℝ) ≤ 0 - y0 := by linarith
            rcases le_total x2 (0 : ℝ) with hbr20 | hbr20
            · have hbr20n : (0 : ℝ) ≤ 0 - x2 := by linarith
              linarith [mul_nonneg hx1 hx13, mul_nonneg hx5 hy12, mul_nonneg hx6 hy4,
                mul_nonneg hx8 hx12, mul_nonneg hx8 hy3, mul_nonneg hx8 hy8, mul_nonneg hx8 hbr19n,
                mul_nonneg hx9 hx11, mul_nonneg hx11 hy11, mul_nonneg hx11 hy12,
                mul_nonneg hx11 hbr18n, mul_nonneg hx11 hbr20n, mul_nonneg hx13 hx14,
                mul_nonneg hx13 hy10, mul_nonneg hx13 hbr0n, mul_nonneg hx14 hy9,
                mul_nonneg hx14 hy12, mul_nonneg hy4 hy11, mul_nonneg hy4 hbr20n,
                mul_nonneg hy9 hy10, mul_nonneg hy12 hbr19n]
            · have hbr20n : (0 : ℝ) ≤ x2 - (0) := by linarith
              linarith [mul_nonneg hx0 hx13, mul_nonneg hx2 hy2, mul_nonneg hx2 hy10,
                mul_nonneg hx2 hbr20n, mul_nonneg hx4 hy12, mul_nonneg hx8 hx12,
                mul_nonneg hx8 hy9, mul_nonneg hx8 hy14, mul_nonneg hx8 hbr16n,
                mul_nonneg hx8 hbr18n, mul_nonneg hx8 hbr19n, mul_nonneg hx9 hy9,
                mul_nonneg hx13 hy11, mul_nonneg hx13 hy14, mul_nonneg hx13 hbr0n,
                mul_nonneg hx13 hbr18n, mul_nonneg hx13 hbr19n, mul_nonneg hy4 hy11,
                mul_nonneg hy9 hy10, mul_nonneg hy9 hbr20n, mul_nonneg hy11 hbr20n,
                mul_nonneg hy12 hbr16n, mul_nonneg hy12 hbr19n]
          · have hbr19n : (0 : ℝ) ≤ y0 - (0) := by linarith
            linarith [mul_nonneg hx0 hx8, mul_nonneg hx0 hx11, mul_nonneg hx1 hx13,
              mul_nonneg hx2 hx14, mul_nonneg hx2 hy10, mul_nonneg hx8 hy14, mul_nonneg hx8 hbr18n,
              mul_nonneg hx11 hy14, mul_nonneg hx11 hbr16n, mul_nonneg hx13 hy10,
              mul_nonneg hx13 hbr0n, mul_nonneg hx14 hy9, mul_nonneg hx14 hy14,
              mul_nonneg hy0 hy11, mul_nonneg hy0 hbr16n, mul_nonneg hy2 hbr19n,
              mul_nonneg hy4 hy11, mul_nonneg hy4 hy14, mul_nonneg hy4 hbr16n, mul_nonneg hy9 hy10,
              mul_nonneg hy9 hbr0n, mul_nonneg hbr0n hbr19n, mul_nonneg hbr17n hbr19n,
              mul_nonneg hbr18n hbr19n]
      · have hbr17n : (0 : ℝ) ≤ y0 - (1 / 2) := by linarith
        linarith [mul_nonneg hx0 hx11, mul_nonneg hx0 hy0, mul_nonneg hx0 hbr16n,
          mul_nonneg hx1 hx11, mul_nonneg hx1 hy1, mul_nonneg hx1 hbr16n, mul_nonneg hx8 hx12,
          mul_nonneg hx9 hx13, mul_nonneg hx12 hx13, mul_nonneg hx12 hy9, mul_nonneg hx12 hbr17n,
          mul_nonneg hx13 hy8, mul_nonneg hx13 hbr0n, mul_nonneg hx14 hy1, mul_nonneg hy0 hy1,
          mul_nonneg hy0 hy14, mul_nonneg hy0 hbr16n, mul_nonneg hy1 hbr0n, mul_nonneg hy1 hbr17n,
          mul_nonneg hy8 hy9, mul_nonneg hy8 hbr17n, mul_nonneg hy9 hbr0n]
    · have hbr16n : (0 : ℝ) ≤ x2 - (1 / 2) := by linarith
      rcases le_total y0 (1 / 2 : ℝ) with hbr21 | hbr21
      · have hbr21n : (0 : ℝ) ≤ 1 / 2 - y0 := by linarith
        rcases le_total x0 (1 / 2 : ℝ) with hbr22 | hbr22
        · have hbr22n : (0 : ℝ) ≤ 1 / 2 - x0 := by linarith
          rcases le_total y0 (0 : ℝ) with hbr23 | hbr23
          · have hbr23n : (0 : ℝ) ≤ 0 - y0 := by linarith
            linarith [mul_nonneg hx0 hx13, mul_nonneg hx2 hx12, mul_nonneg hx2 hbr0n,
              mul_nonneg hx2 hbr23n, mul_nonneg hx9 hy9, mul_nonneg hx10 hy4, mul_nonneg hx10 hy10,
              mul_nonneg hx10 hy12, mul_nonneg hx10 hbr16n, mul_nonneg hx10 hbr22n,
              mul_nonneg hx12 hy9, mul_nonneg hx12 hy11, mul_nonneg hx13 hy12,
              mul_nonneg hx13 hbr0n, mul_nonneg hx13 hbr16n, mul_nonneg hy2 hy9,
              mul_nonneg hy4 hy14, mul_nonneg hy9 hbr0n, mul_nonneg hy10 hy11,
              mul_nonneg hy11 hbr0n, mul_nonneg hy11 hbr23n, mul_nonneg hy12 hy14,
              mul_nonneg hy14 hbr16n, mul_nonneg hy14 hbr22n]
          · have hbr23n : (0 : ℝ) ≤ y0 - (0) := by linarith
            linarith [mul_nonneg hx0 hx10, mul_nonneg hx2 hbr21n, mul_nonneg hx4 hx13,
              mul_nonneg hx4 hy9, mul_nonneg hx10 hy10, mul_nonneg hx10 hbr0n,
              mul_nonneg hx10 hbr16n, mul_nonneg hx10 hbr23n, mul_nonneg hx11 hbr22n,
              mul_nonneg hx11 hbr23n, mul_nonneg hx12 hy14, mul_nonneg hx12 hbr23n,
              mul_nonneg hx13 hbr0n, mul_nonneg hx13 hbr21n, mul_nonneg hy0 hy9,
              mul_nonneg hy0 hy14, mul_nonneg hy1 hbr16n, mul_nonneg hy1 hbr22n,
              mul_nonneg hy1 hbr23n, mul_nonneg hy9 hbr0n, mul_nonneg hy9 hbr21n,
              mul_nonneg hy14 hbr0n, mul_nonneg hy14 hbr16n]
        · have hbr22n : (0 : ℝ) ≤ x0 - (1 / 2) := by linarith
          linarith [mul_nonneg hx0 hx13, mul_nonneg hx0 hy9, mul_nonneg hx2 hx5,
            mul_nonneg hx2 hx9, mul_nonneg hx2 hy13, mul_nonneg hx2 hbr0n, mul_nonneg hx8 hbr22n,
            mul_nonneg hx10 hbr16n, mul_nonneg hy0 hy11, mul_nonneg hy2 hy9, mul_nonneg hy9 hy10,
            mul_nonneg hy9 hbr0n, mul_nonneg hy9 hbr21n, mul_nonneg hy11 hbr0n,
            mul_nonneg hy12 hy14, mul_nonneg hy12 hbr22n, mul_nonneg hy14 hbr16n,
            mul_nonneg hbr16n hbr22n]
      · have hbr21n : (0 : ℝ) ≤ y0 - (1 / 2) := by linarith
        linarith [mul_nonneg hx0 hx10, mul_nonneg hx0 hx11, mul_nonneg hx1 hx10,
          mul_nonneg hx10 hy0, mul_nonneg hx10 hbr16n, mul_nonneg hx11 hbr16n,
          mul_nonneg hx12 hx13, mul_nonneg hx12 hbr21n, mul_nonneg hx13 hbr0n, mul_nonneg hx14 hy1,
          mul_nonneg hy0 hy14, mul_nonneg hy1 hy6, mul_nonneg hy1 hy10, mul_nonneg hy1 hbr16n,
          mul_nonneg hy8 hbr21n, mul_nonneg hy9 hbr0n, mul_nonneg hbr0n hbr21n]

set_option maxHeartbeats 1600000 in
-- the branch-and-certify case tree is large
@[category API, AMS 52]
theorem certC11 (x0 x1 x2 y0 y1 y2 : ℝ)
    (hx0 : (0 : ℝ) ≤ 3 / 2 - (x0 + x1 + x2)) (hx1 : (0 : ℝ) ≤ 3 / 2 - (x0 + x1 - x2))
    (hx2 : (0 : ℝ) ≤ 3 / 2 - (x0 - x1 + x2)) (hx3 : (0 : ℝ) ≤ 3 / 2 - (x0 - x1 - x2))
    (hx4 : (0 : ℝ) ≤ 3 / 2 - (-x0 + x1 + x2)) (hx5 : (0 : ℝ) ≤ 3 / 2 - (-x0 + x1 - x2))
    (hx6 : (0 : ℝ) ≤ 3 / 2 - (-x0 - x1 + x2)) (hx7 : (0 : ℝ) ≤ 3 / 2 - (-x0 - x1 - x2))
    (hx8 : (0 : ℝ) ≤ 13 / 15 - x0) (hx9 : (0 : ℝ) ≤ 13 / 15 - x1)
    (hx10 : (0 : ℝ) ≤ 13 / 15 - x2) (hx11 : (0 : ℝ) ≤ 5 / 12 - (x0 + x1 + x2))
    (hx12 : (0 : ℝ) ≤ x1 - x0) (hx13 : (0 : ℝ) ≤ x2 - x0)
    (hy0 : (0 : ℝ) ≤ 3 / 2 - (y0 + y1 + y2)) (hy1 : (0 : ℝ) ≤ 3 / 2 - (y0 + y1 - y2))
    (hy2 : (0 : ℝ) ≤ 3 / 2 - (y0 - y1 + y2)) (hy3 : (0 : ℝ) ≤ 3 / 2 - (y0 - y1 - y2))
    (hy4 : (0 : ℝ) ≤ 3 / 2 - (-y0 + y1 + y2)) (hy5 : (0 : ℝ) ≤ 3 / 2 - (-y0 + y1 - y2))
    (hy6 : (0 : ℝ) ≤ 3 / 2 - (-y0 - y1 + y2)) (hy7 : (0 : ℝ) ≤ 3 / 2 - (-y0 - y1 - y2))
    (hy8 : (0 : ℝ) ≤ 13 / 15 - y0) (hy9 : (0 : ℝ) ≤ 13 / 15 - y1)
    (hy10 : (0 : ℝ) ≤ 13 / 15 - y2) (hy11 : (0 : ℝ) ≤ 5 / 12 - (y0 + y1 + y2))
    (hy12 : (0 : ℝ) ≤ y1 - y0) (hy13 : (0 : ℝ) ≤ y2 - y0)
    :
    (x0 - y0) ^ 2 + (x1 - y1) ^ 2 + (x2 - y2) ^ 2 ≤ 149 / 50 := by
  rcases le_total y2 (0 : ℝ) with hbr0 | hbr0
  · have hbr0n : (0 : ℝ) ≤ 0 - y2 := by linarith
    rcases le_total x2 (0 : ℝ) with hbr1 | hbr1
    · have hbr1n : (0 : ℝ) ≤ 0 - x2 := by linarith
      rcases le_total y1 (0 : ℝ) with hbr2 | hbr2
      · have hbr2n : (0 : ℝ) ≤ 0 - y1 := by linarith
        linarith [mul_nonneg hx4 hx13, mul_nonneg hx4 hbr0n, mul_nonneg hx5 hx11,
          mul_nonneg hx5 hx13, mul_nonneg hx5 hy7, mul_nonneg hx5 hbr1n, mul_nonneg hx6 hx9,
          mul_nonneg hx6 hx13, mul_nonneg hx6 hy6, mul_nonneg hx6 hbr0n, mul_nonneg hx7 hx9,
          mul_nonneg hx7 hx11, mul_nonneg hx7 hy7, mul_nonneg hx9 hx12, mul_nonneg hx9 hbr2n,
          mul_nonneg hx12 hy12, mul_nonneg hx13 hy12, mul_nonneg hy5 hy12, mul_nonneg hy6 hy13,
          mul_nonneg hy6 hbr1n, mul_nonneg hy7 hbr0n, mul_nonneg hy7 hbr2n, mul_nonneg hy12 hbr1n]
      · have hbr2n : (0 : ℝ) ≤ y1 - (0) := by linarith
        rcases le_total y0 (-1 : ℝ) with hbr3 | hbr3
        · have hbr3n : (0 : ℝ) ≤ -1 - y0 := by linarith
          linarith [mul_nonneg hx4 hx13, mul_nonneg hx4 hy4, mul_nonneg hx4 hbr0n,
            mul_nonneg hx5 hx13, mul_nonneg hx5 hy5, mul_nonneg hx5 hbr1n, mul_nonneg hx6 hx11,
            mul_nonneg hx6 hx13, mul_nonneg hx6 hbr0n, mul_nonneg hx6 hbr2n, mul_nonneg hx7 hx11,
            mul_nonneg hx7 hy7, mul_nonneg hx7 hbr2n, mul_nonneg hx9 hx12, mul_nonneg hx9 hbr1n,
            mul_nonneg hx11 hx12, mul_nonneg hx11 hbr3n, mul_nonneg hx12 hbr2n,
            mul_nonneg hx13 hbr3n, mul_nonneg hy4 hy13, mul_nonneg hy4 hbr1n, mul_nonneg hy5 hy12,
            mul_nonneg hy5 hbr2n, mul_nonneg hy7 hbr0n, mul_nonneg hbr2n hbr3n]
        · have hbr3n : (0 : ℝ) ≤ y0 - (-1) := by linarith
          linarith [mul_nonneg hx5 hx12, mul_nonneg hx5 hy9, mul_nonneg hx6 hx11,
            mul_nonneg hx6 hbr2n, mul_nonneg hx6 hbr3n, mul_nonneg hx7 hx11, mul_nonneg hx7 hy7,
            mul_nonneg hx7 hbr2n, mul_nonneg hx7 hbr3n, mul_nonneg hx9 hy9, mul_nonneg hx12 hy12,
            mul_nonneg hx12 hy13, mul_nonneg hx12 hbr0n, mul_nonneg hx13 hy11,
            mul_nonneg hx13 hy13, mul_nonneg hx13 hbr1n, mul_nonneg hy4 hy13, mul_nonneg hy5 hy11,
            mul_nonneg hy9 hbr0n, mul_nonneg hy9 hbr2n, mul_nonneg hy11 hbr1n,
            mul_nonneg hy11 hbr3n, mul_nonneg hy13 hbr0n, mul_nonneg hy13 hbr3n,
            mul_nonneg hbr0n hbr1n]
    · have hbr1n : (0 : ℝ) ≤ x2 - (0) := by linarith
      rcases le_total y1 (0 : ℝ) with hbr4 | hbr4
      · have hbr4n : (0 : ℝ) ≤ 0 - y1 := by linarith
        rcases le_total x1 (0 : ℝ) with hbr5 | hbr5
        · have hbr5n : (0 : ℝ) ≤ 0 - x1 := by linarith
          linarith [mul_nonneg hx1 hbr4n, mul_nonneg hx4 hx12, mul_nonneg hx4 hy5,
            mul_nonneg hx5 hx10, mul_nonneg hx5 hx12, mul_nonneg hx5 hbr4n, mul_nonneg hx6 hx11,
            mul_nonneg hx6 hy7, mul_nonneg hx7 hy7, mul_nonneg hx10 hy6, mul_nonneg hx10 hbr0n,
            mul_nonneg hx10 hbr1n, mul_nonneg hx11 hy1, mul_nonneg hx11 hy11, mul_nonneg hx11 hy13,
            mul_nonneg hx12 hy12, mul_nonneg hx12 hy13, mul_nonneg hx13 hy13, mul_nonneg hy5 hy12,
            mul_nonneg hy5 hbr5n, mul_nonneg hy6 hy13, mul_nonneg hy7 hy11, mul_nonneg hy7 hbr4n,
            mul_nonneg hy13 hbr0n]
        · have hbr5n : (0 : ℝ) ≤ x1 - (0) := by linarith
          linarith [mul_nonneg hx4 hx11, mul_nonneg hx4 hx12, mul_nonneg hx4 hx13,
            mul_nonneg hx4 hy4, mul_nonneg hx4 hy7, mul_nonneg hx5 hx11, mul_nonneg hx6 hx11,
            mul_nonneg hx7 hy7, mul_nonneg hx9 hbr4n, mul_nonneg hx9 hbr5n, mul_nonneg hx10 hbr0n,
            mul_nonneg hx10 hbr1n, mul_nonneg hx11 hy11, mul_nonneg hx11 hy12,
            mul_nonneg hx11 hy13, mul_nonneg hx12 hy12, mul_nonneg hx13 hy13, mul_nonneg hy4 hy7,
            mul_nonneg hy5 hy12, mul_nonneg hy6 hy13, mul_nonneg hy7 hy11, mul_nonneg hy7 hbr0n,
            mul_nonneg hy12 hbr4n, mul_nonneg hbr1n hbr5n]
      · have hbr4n : (0 : ℝ) ≤ y1 - (0) := by linarith
        rcases le_total x0 (-1 / 2 : ℝ) with hbr6 | hbr6
        · have hbr6n : (0 : ℝ) ≤ -1 / 2 - x0 := by linarith
          linarith [mul_nonneg hx4 hx12, mul_nonneg hx4 hy9, mul_nonneg hx5 hy5,
            mul_nonneg hx6 hx9, mul_nonneg hx6 hy6, mul_nonneg hx6 hbr0n, mul_nonneg hx6 hbr4n,
            mul_nonneg hx7 hy7, mul_nonneg hx7 hbr6n, mul_nonneg hx10 hy9, mul_nonneg hx10 hy11,
            mul_nonneg hx10 hbr0n, mul_nonneg hx10 hbr1n, mul_nonneg hx12 hy13,
            mul_nonneg hx12 hbr4n, mul_nonneg hy4 hy13, mul_nonneg hy5 hy11, mul_nonneg hy5 hbr1n,
            mul_nonneg hy6 hy13, mul_nonneg hy9 hbr4n, mul_nonneg hy11 hbr6n,
            mul_nonneg hy13 hbr1n, mul_nonneg hy13 hbr6n]
        · have hbr6n : (0 : ℝ) ≤ x0 - (-1 / 2) := by linarith
          rcases le_total y1 (1 / 2 : ℝ) with hbr7 | hbr7
          · have hbr7n : (0 : ℝ) ≤ 1 / 2 - y1 := by linarith
            linarith [mul_nonneg hx4 hx12, mul_nonneg hx5 hx12, mul_nonneg hx5 hy5,
              mul_nonneg hx6 hx11, mul_nonneg hx6 hy7, mul_nonneg hx6 hbr4n, mul_nonneg hx7 hy7,
              mul_nonneg hx10 hy4, mul_nonneg hx10 hy11, mul_nonneg hx10 hbr0n,
              mul_nonneg hx10 hbr1n, mul_nonneg hx11 hy13, mul_nonneg hx11 hbr7n,
              mul_nonneg hx12 hy13, mul_nonneg hx12 hbr4n, mul_nonneg hx13 hy13,
              mul_nonneg hy5 hy11, mul_nonneg hy5 hy12, mul_nonneg hy6 hy13, mul_nonneg hy7 hy11,
              mul_nonneg hy7 hbr6n, mul_nonneg hy7 hbr7n, mul_nonneg hy13 hbr0n]
          · have hbr7n : (0 : ℝ) ≤ y1 - (1 / 2) := by linarith
            linarith [mul_nonneg hx4 hx12, mul_nonneg hx5 hx12, mul_nonneg hx6 hx11,
              mul_nonneg hx6 hy6, mul_nonneg hx6 hbr1n, mul_nonneg hx6 hbr4n, mul_nonneg hx7 hy5,
              mul_nonneg hx10 hy11, mul_nonneg hx10 hbr1n, mul_nonneg hx10 hbr6n,
              mul_nonneg hx11 hy9, mul_nonneg hx12 hy12, mul_nonneg hx12 hy13,
              mul_nonneg hx12 hbr7n, mul_nonneg hx13 hy13, mul_nonneg hy4 hy13,
              mul_nonneg hy5 hy11, mul_nonneg hy5 hy12, mul_nonneg hy5 hbr0n, mul_nonneg hy5 hbr1n,
              mul_nonneg hy5 hbr6n, mul_nonneg hy7 hy9, mul_nonneg hy9 hbr4n, mul_nonneg hy9 hbr7n,
              mul_nonneg hy13 hbr1n, mul_nonneg hy13 hbr7n]
  · have hbr0n : (0 : ℝ) ≤ y2 - (0) := by linarith
    rcases le_total y0 (-1 / 2 : ℝ) with hbr8 | hbr8
    · have hbr8n : (0 : ℝ) ≤ -1 / 2 - y0 := by linarith
      rcases le_total x2 (0 : ℝ) with hbr9 | hbr9
      · have hbr9n : (0 : ℝ) ≤ 0 - x2 := by linarith
        rcases le_total x1 (0 : ℝ) with hbr10 | hbr10
        · have hbr10n : (0 : ℝ) ≤ 0 - x1 := by linarith
          linarith [mul_nonneg hx5 hx12, mul_nonneg hx5 hy4, mul_nonneg hx5 hy9,
            mul_nonneg hx6 hx13, mul_nonneg hx6 hy10, mul_nonneg hx7 hy4, mul_nonneg hx7 hy7,
            mul_nonneg hx7 hbr9n, mul_nonneg hx7 hbr10n, mul_nonneg hx12 hy6, mul_nonneg hx12 hy10,
            mul_nonneg hx12 hbr8n, mul_nonneg hx13 hy9, mul_nonneg hx13 hbr0n,
            mul_nonneg hx13 hbr8n, mul_nonneg hy4 hy12, mul_nonneg hy4 hbr8n, mul_nonneg hy5 hbr8n,
            mul_nonneg hy6 hy9, mul_nonneg hy7 hy11, mul_nonneg hy9 hbr10n, mul_nonneg hy10 hbr0n,
            mul_nonneg hy10 hbr9n, mul_nonneg hy11 hbr0n, mul_nonneg hy11 hbr10n]
        · have hbr10n : (0 : ℝ) ≤ x1 - (0) := by linarith
          linarith [mul_nonneg hx4 hx13, mul_nonneg hx5 hx11, mul_nonneg hx5 hy5,
            mul_nonneg hx5 hbr0n, mul_nonneg hx6 hx13, mul_nonneg hx6 hy6, mul_nonneg hx7 hy7,
            mul_nonneg hx9 hy4, mul_nonneg hx9 hy10, mul_nonneg hx9 hbr10n, mul_nonneg hx11 hy10,
            mul_nonneg hx11 hbr8n, mul_nonneg hx13 hy12, mul_nonneg hx13 hbr0n,
            mul_nonneg hx13 hbr8n, mul_nonneg hy4 hy12, mul_nonneg hy6 hy9, mul_nonneg hy6 hbr9n,
            mul_nonneg hy6 hbr10n, mul_nonneg hy7 hbr8n, mul_nonneg hy10 hbr0n,
            mul_nonneg hy10 hbr9n, mul_nonneg hy12 hbr10n]
      · have hbr9n : (0 : ℝ) ≤ x2 - (0) := by linarith
        linarith [mul_nonneg hx4 hx12, mul_nonneg hx4 hy4, mul_nonneg hx5 hx12, mul_nonneg hx5 hy5,
          mul_nonneg hx5 hbr0n, mul_nonneg hx6 hx11, mul_nonneg hx6 hy6, mul_nonneg hx6 hbr9n,
          mul_nonneg hx7 hx11, mul_nonneg hx7 hbr0n, mul_nonneg hx9 hy4, mul_nonneg hx11 hy9,
          mul_nonneg hx11 hbr8n, mul_nonneg hx12 hy6, mul_nonneg hx12 hy12, mul_nonneg hx13 hbr8n,
          mul_nonneg hy2 hbr0n, mul_nonneg hy3 hbr9n, mul_nonneg hy4 hy12, mul_nonneg hy5 hbr9n,
          mul_nonneg hy6 hy9, mul_nonneg hy6 hbr0n, mul_nonneg hy7 hy9, mul_nonneg hy7 hbr8n,
          mul_nonneg hy7 hbr9n, mul_nonneg hy11 hbr0n]
    · have hbr8n : (0 : ℝ) ≤ y0 - (-1 / 2) := by linarith
      rcases le_total x1 (0 : ℝ) with hbr11 | hbr11
      · have hbr11n : (0 : ℝ) ≤ 0 - x1 := by linarith
        rcases le_total y1 (0 : ℝ) with hbr12 | hbr12
        · have hbr12n : (0 : ℝ) ≤ 0 - y1 := by linarith
          linarith [mul_nonneg hx4 hy10, mul_nonneg hx5 hx11, mul_nonneg hx5 hx12,
            mul_nonneg hx5 hbr0n, mul_nonneg hx5 hbr8n, mul_nonneg hx6 hx13, mul_nonneg hx6 hy10,
            mul_nonneg hx7 hx10, mul_nonneg hx7 hx11, mul_nonneg hx7 hy7, mul_nonneg hx10 hy10,
            mul_nonneg hx12 hy11, mul_nonneg hx12 hy12, mul_nonneg hx12 hbr11n,
            mul_nonneg hx13 hy11, mul_nonneg hx13 hy13, mul_nonneg hx13 hbr12n,
            mul_nonneg hy5 hbr11n, mul_nonneg hy6 hy11, mul_nonneg hy10 hy13,
            mul_nonneg hy10 hbr0n, mul_nonneg hy11 hbr8n, mul_nonneg hy11 hbr11n,
            mul_nonneg hy12 hbr8n, mul_nonneg hy12 hbr12n]
        · have hbr12n : (0 : ℝ) ≤ y1 - (0) := by linarith
          linarith [mul_nonneg hx4 hbr8n, mul_nonneg hx5 hx12, mul_nonneg hx5 hy9,
            mul_nonneg hx6 hx13, mul_nonneg hx6 hy10, mul_nonneg hx7 hx10, mul_nonneg hx7 hx11,
            mul_nonneg hx7 hy7, mul_nonneg hx7 hbr0n, mul_nonneg hx7 hbr8n, mul_nonneg hx11 hy11,
            mul_nonneg hx12 hy11, mul_nonneg hx12 hy12, mul_nonneg hx12 hbr11n,
            mul_nonneg hx12 hbr12n, mul_nonneg hx13 hy11, mul_nonneg hx13 hy13,
            mul_nonneg hx13 hbr0n, mul_nonneg hy9 hbr11n, mul_nonneg hy11 hy13,
            mul_nonneg hy11 hbr0n, mul_nonneg hy11 hbr12n, mul_nonneg hy12 hbr8n,
            mul_nonneg hy13 hbr8n, mul_nonneg hbr0n hbr12n]
      · have hbr11n : (0 : ℝ) ≤ x1 - (0) := by linarith
        rcases le_total x0 (-1 / 2 : ℝ) with hbr13 | hbr13
        · have hbr13n : (0 : ℝ) ≤ -1 / 2 - x0 := by linarith
          linarith [mul_nonneg hx2 hx5, mul_nonneg hx4 hx13, mul_nonneg hx4 hy10,
            mul_nonneg hx5 hy9, mul_nonneg hx5 hbr0n, mul_nonneg hx5 hbr11n, mul_nonneg hx6 hx13,
            mul_nonneg hx7 hx11, mul_nonneg hx7 hbr0n, mul_nonneg hx7 hbr8n, mul_nonneg hx11 hy10,
            mul_nonneg hx11 hy11, mul_nonneg hx12 hy12, mul_nonneg hx13 hy12, mul_nonneg hx13 hy13,
            mul_nonneg hy6 hy11, mul_nonneg hy6 hbr11n, mul_nonneg hy9 hy12, mul_nonneg hy10 hbr0n,
            mul_nonneg hy11 hbr13n, mul_nonneg hy12 hbr8n, mul_nonneg hy12 hbr11n,
            mul_nonneg hy12 hbr13n, mul_nonneg hbr11n hbr13n]
        · have hbr13n : (0 : ℝ) ≤ x0 - (-1 / 2) := by linarith
          linarith [mul_nonneg hx4 hx13, mul_nonneg hx5 hx10, mul_nonneg hx5 hx11,
            mul_nonneg hx5 hx12, mul_nonneg hx5 hbr0n, mul_nonneg hx5 hbr8n, mul_nonneg hx9 hy11,
            mul_nonneg hx9 hbr11n, mul_nonneg hx9 hbr13n, mul_nonneg hx11 hy10,
            mul_nonneg hx12 hy12, mul_nonneg hx13 hy13, mul_nonneg hx13 hbr0n,
            mul_nonneg hx13 hbr13n, mul_nonneg hy1 hy6, mul_nonneg hy4 hy12, mul_nonneg hy6 hy11,
            mul_nonneg hy6 hy13, mul_nonneg hy6 hbr0n, mul_nonneg hy6 hbr11n,
            mul_nonneg hy6 hbr13n, mul_nonneg hy9 hy12, mul_nonneg hy10 hbr0n,
            mul_nonneg hy10 hbr8n, mul_nonneg hy12 hbr8n, mul_nonneg hy12 hbr11n]

set_option maxHeartbeats 1600000 in
-- the branch-and-certify case tree is large
@[category API, AMS 52]
theorem certC22 (x0 x1 x2 y0 y1 y2 : ℝ)
    (hx0 : (0 : ℝ) ≤ 3 / 2 - (x0 + x1 + x2)) (hx1 : (0 : ℝ) ≤ 3 / 2 - (x0 + x1 - x2))
    (hx2 : (0 : ℝ) ≤ 3 / 2 - (x0 - x1 + x2)) (hx3 : (0 : ℝ) ≤ 3 / 2 - (x0 - x1 - x2))
    (hx4 : (0 : ℝ) ≤ 3 / 2 - (-x0 + x1 + x2)) (hx5 : (0 : ℝ) ≤ 3 / 2 - (-x0 + x1 - x2))
    (hx6 : (0 : ℝ) ≤ 3 / 2 - (-x0 - x1 + x2)) (hx7 : (0 : ℝ) ≤ 3 / 2 - (-x0 - x1 - x2))
    (hx8 : (0 : ℝ) ≤ 13 / 15 - x0) (hx9 : (0 : ℝ) ≤ 13 / 15 - x1)
    (hx10 : (0 : ℝ) ≤ 13 / 15 - x2) (hx11 : (0 : ℝ) ≤ -(7 / 24) - x0)
    (hx12 : (0 : ℝ) ≤ x1 - x0) (hx13 : (0 : ℝ) ≤ x2 - x0)
    (hy0 : (0 : ℝ) ≤ 3 / 2 - (y0 + y1 + y2)) (hy1 : (0 : ℝ) ≤ 3 / 2 - (y0 + y1 - y2))
    (hy2 : (0 : ℝ) ≤ 3 / 2 - (y0 - y1 + y2)) (hy3 : (0 : ℝ) ≤ 3 / 2 - (y0 - y1 - y2))
    (hy4 : (0 : ℝ) ≤ 3 / 2 - (-y0 + y1 + y2)) (hy5 : (0 : ℝ) ≤ 3 / 2 - (-y0 + y1 - y2))
    (hy6 : (0 : ℝ) ≤ 3 / 2 - (-y0 - y1 + y2)) (hy7 : (0 : ℝ) ≤ 3 / 2 - (-y0 - y1 - y2))
    (hy8 : (0 : ℝ) ≤ 13 / 15 - y0) (hy9 : (0 : ℝ) ≤ 13 / 15 - y1)
    (hy10 : (0 : ℝ) ≤ 13 / 15 - y2) (hy11 : (0 : ℝ) ≤ -(7 / 24) - y0)
    (hy12 : (0 : ℝ) ≤ y1 - y0) (hy13 : (0 : ℝ) ≤ y2 - y0)
    :
    (x0 - y0) ^ 2 + (x1 - y1) ^ 2 + (x2 - y2) ^ 2 ≤ 149 / 50 := by
  rcases le_total y2 (0 : ℝ) with hbr0 | hbr0
  · have hbr0n : (0 : ℝ) ≤ 0 - y2 := by linarith
    rcases le_total x1 (0 : ℝ) with hbr1 | hbr1
    · have hbr1n : (0 : ℝ) ≤ 0 - x1 := by linarith
      rcases le_total x2 (0 : ℝ) with hbr2 | hbr2
      · have hbr2n : (0 : ℝ) ≤ 0 - x2 := by linarith
        linarith [mul_nonneg hx0 hx7, mul_nonneg hx1 hy9, mul_nonneg hx4 hx12, mul_nonneg hx5 hx12,
          mul_nonneg hx5 hbr2n, mul_nonneg hx6 hx13, mul_nonneg hx6 hy4, mul_nonneg hx6 hbr0n,
          mul_nonneg hx7 hy5, mul_nonneg hx7 hy7, mul_nonneg hx7 hbr1n, mul_nonneg hx12 hy11,
          mul_nonneg hx12 hy12, mul_nonneg hx12 hbr0n, mul_nonneg hx12 hbr1n, mul_nonneg hx13 hy11,
          mul_nonneg hx13 hy13, mul_nonneg hy2 hbr2n, mul_nonneg hy5 hy11, mul_nonneg hy6 hy9,
          mul_nonneg hy6 hbr2n, mul_nonneg hy7 hy9, mul_nonneg hy9 hbr1n, mul_nonneg hy13 hbr0n,
          mul_nonneg hbr0n hbr2n]
      · have hbr2n : (0 : ℝ) ≤ x2 - (0) := by linarith
        rcases le_total y1 (0 : ℝ) with hbr3 | hbr3
        · have hbr3n : (0 : ℝ) ≤ 0 - y1 := by linarith
          linarith [mul_nonneg hx0 hbr3n, mul_nonneg hx4 hy5, mul_nonneg hx4 hbr3n,
            mul_nonneg hx5 hx10, mul_nonneg hx5 hbr3n, mul_nonneg hx6 hx11, mul_nonneg hx6 hy7,
            mul_nonneg hx7 hx10, mul_nonneg hx7 hy7, mul_nonneg hx10 hy2, mul_nonneg hx10 hbr0n,
            mul_nonneg hx11 hy11, mul_nonneg hx11 hy13, mul_nonneg hx12 hy2, mul_nonneg hx12 hbr1n,
            mul_nonneg hx13 hy13, mul_nonneg hy0 hy7, mul_nonneg hy2 hy5, mul_nonneg hy4 hy13,
            mul_nonneg hy5 hy12, mul_nonneg hy5 hbr1n, mul_nonneg hy6 hy13, mul_nonneg hy7 hbr0n,
            mul_nonneg hy12 hbr3n]
        · have hbr3n : (0 : ℝ) ≤ y1 - (0) := by linarith
          rcases le_total y1 (1 / 2 : ℝ) with hbr4 | hbr4
          · have hbr4n : (0 : ℝ) ≤ 1 / 2 - y1 := by linarith
            linarith [mul_nonneg hx1 hy13, mul_nonneg hx5 hx10, mul_nonneg hx5 hy5,
              mul_nonneg hx6 hx11, mul_nonneg hx6 hy7, mul_nonneg hx6 hbr3n, mul_nonneg hx7 hx10,
              mul_nonneg hx7 hx11, mul_nonneg hx7 hy7, mul_nonneg hx7 hbr3n, mul_nonneg hx10 hy0,
              mul_nonneg hx10 hbr0n, mul_nonneg hx10 hbr2n, mul_nonneg hx10 hbr4n,
              mul_nonneg hx11 hy13, mul_nonneg hx12 hy12, mul_nonneg hx12 hbr1n,
              mul_nonneg hx12 hbr2n, mul_nonneg hx12 hbr3n, mul_nonneg hx13 hy13,
              mul_nonneg hy4 hy13, mul_nonneg hy5 hy11, mul_nonneg hy5 hbr0n, mul_nonneg hy6 hy13,
              mul_nonneg hy7 hbr4n, mul_nonneg hbr3n hbr4n]
          · have hbr4n : (0 : ℝ) ≤ y1 - (1 / 2) := by linarith
            linarith [mul_nonneg hx0 hy9, mul_nonneg hx1 hx6, mul_nonneg hx4 hx12,
              mul_nonneg hx5 hx12, mul_nonneg hx6 hx13, mul_nonneg hx6 hy4, mul_nonneg hx6 hy6,
              mul_nonneg hx6 hbr1n, mul_nonneg hx7 hx10, mul_nonneg hx7 hx11, mul_nonneg hx7 hy5,
              mul_nonneg hx7 hbr4n, mul_nonneg hx10 hy9, mul_nonneg hx12 hy0, mul_nonneg hx12 hy11,
              mul_nonneg hx12 hy12, mul_nonneg hx13 hy13, mul_nonneg hy5 hy9, mul_nonneg hy5 hy11,
              mul_nonneg hy5 hbr2n, mul_nonneg hy9 hbr1n, mul_nonneg hy9 hbr4n,
              mul_nonneg hy11 hbr4n, mul_nonneg hy13 hbr0n, mul_nonneg hy13 hbr2n,
              mul_nonneg hy13 hbr4n]
    · have hbr1n : (0 : ℝ) ≤ x1 - (0) := by linarith
      rcases le_total y1 (0 : ℝ) with hbr5 | hbr5
      · have hbr5n : (0 : ℝ) ≤ 0 - y1 := by linarith
        rcases le_total x2 (0 : ℝ) with hbr6 | hbr6
        · have hbr6n : (0 : ℝ) ≤ 0 - x2 := by linarith
          linarith [mul_nonneg hx0 hbr0n, mul_nonneg hx2 hbr0n, mul_nonneg hx3 hx9,
            mul_nonneg hx5 hx11, mul_nonneg hx6 hx9, mul_nonneg hx6 hy6, mul_nonneg hx6 hbr0n,
            mul_nonneg hx7 hx9, mul_nonneg hx7 hx11, mul_nonneg hx7 hy7, mul_nonneg hx9 hy5,
            mul_nonneg hx9 hy9, mul_nonneg hx9 hbr5n, mul_nonneg hx11 hy11, mul_nonneg hx11 hy12,
            mul_nonneg hx12 hy12, mul_nonneg hx13 hy13, mul_nonneg hx13 hbr6n, mul_nonneg hy0 hy7,
            mul_nonneg hy4 hy12, mul_nonneg hy5 hy12, mul_nonneg hy6 hy13, mul_nonneg hy6 hbr5n,
            mul_nonneg hy7 hbr0n, mul_nonneg hy12 hbr6n, mul_nonneg hbr0n hbr6n]
        · have hbr6n : (0 : ℝ) ≤ x2 - (0) := by linarith
          rcases le_total x2 (1 / 2 : ℝ) with hbr7 | hbr7
          · have hbr7n : (0 : ℝ) ≤ 1 / 2 - x2 := by linarith
            linarith [mul_nonneg hx4 hx13, mul_nonneg hx4 hy4, mul_nonneg hx4 hbr6n,
              mul_nonneg hx6 hx9, mul_nonneg hx6 hbr0n, mul_nonneg hx7 hx11, mul_nonneg hx7 hy7,
              mul_nonneg hx9 hy1, mul_nonneg hx9 hy5, mul_nonneg hx9 hy13, mul_nonneg hx9 hbr1n,
              mul_nonneg hx9 hbr5n, mul_nonneg hx9 hbr7n, mul_nonneg hx11 hy11,
              mul_nonneg hx11 hy12, mul_nonneg hx11 hy13, mul_nonneg hx11 hbr6n,
              mul_nonneg hx12 hy12, mul_nonneg hy5 hy12, mul_nonneg hy6 hy13, mul_nonneg hy6 hbr7n,
              mul_nonneg hy7 hbr0n, mul_nonneg hy7 hbr5n, mul_nonneg hy12 hbr7n,
              mul_nonneg hbr0n hbr7n]
          · have hbr7n : (0 : ℝ) ≤ x2 - (1 / 2) := by linarith
            linarith [mul_nonneg hx4 hx6, mul_nonneg hx4 hx7, mul_nonneg hx4 hx12,
              mul_nonneg hx4 hy4, mul_nonneg hx4 hy5, mul_nonneg hx4 hbr1n, mul_nonneg hx4 hbr5n,
              mul_nonneg hx7 hx11, mul_nonneg hx7 hy7, mul_nonneg hx9 hx10, mul_nonneg hx9 hy5,
              mul_nonneg hx9 hy13, mul_nonneg hx9 hbr5n, mul_nonneg hx10 hy12,
              mul_nonneg hx10 hbr0n, mul_nonneg hx10 hbr6n, mul_nonneg hx11 hy13,
              mul_nonneg hx11 hbr1n, mul_nonneg hx11 hbr5n, mul_nonneg hy5 hy12,
              mul_nonneg hy5 hbr7n, mul_nonneg hy6 hy13, mul_nonneg hy7 hbr0n,
              mul_nonneg hy7 hbr5n, mul_nonneg hy13 hbr7n]
      · have hbr5n : (0 : ℝ) ≤ y1 - (0) := by linarith
        linarith [mul_nonneg hx1 hy13, mul_nonneg hx4 hy4, mul_nonneg hx4 hbr1n,
          mul_nonneg hx5 hx10, mul_nonneg hx5 hy5, mul_nonneg hx6 hx11, mul_nonneg hx6 hbr5n,
          mul_nonneg hx7 hy7, mul_nonneg hx9 hy13, mul_nonneg hx10 hbr0n, mul_nonneg hx11 hy0,
          mul_nonneg hx11 hy11, mul_nonneg hx13 hy5, mul_nonneg hx13 hy13, mul_nonneg hy4 hy13,
          mul_nonneg hy5 hy12, mul_nonneg hy5 hbr0n, mul_nonneg hy6 hy13, mul_nonneg hy7 hy9,
          mul_nonneg hy7 hy11, mul_nonneg hy7 hbr0n, mul_nonneg hy7 hbr1n, mul_nonneg hy9 hbr5n,
          mul_nonneg hbr1n hbr5n]
  · have hbr0n : (0 : ℝ) ≤ y2 - (0) := by linarith
    rcases le_total x1 (0 : ℝ) with hbr8 | hbr8
    · have hbr8n : (0 : ℝ) ≤ 0 - x1 := by linarith
      rcases le_total x2 (0 : ℝ) with hbr9 | hbr9
      · have hbr9n : (0 : ℝ) ≤ 0 - x2 := by linarith
        rcases le_total y1 (0 : ℝ) with hbr10 | hbr10
        · have hbr10n : (0 : ℝ) ≤ 0 - y1 := by linarith
          linarith [mul_nonneg hx2 hy12, mul_nonneg hx5 hx12, mul_nonneg hx5 hy4,
            mul_nonneg hx5 hbr10n, mul_nonneg hx6 hx13, mul_nonneg hx6 hy10, mul_nonneg hx7 hy7,
            mul_nonneg hx7 hbr8n, mul_nonneg hx7 hbr9n, mul_nonneg hx11 hy11, mul_nonneg hx12 hy12,
            mul_nonneg hx13 hy1, mul_nonneg hx13 hy11, mul_nonneg hx13 hy13, mul_nonneg hy1 hy10,
            mul_nonneg hy1 hbr8n, mul_nonneg hy5 hy10, mul_nonneg hy5 hbr8n, mul_nonneg hy6 hy11,
            mul_nonneg hy7 hy10, mul_nonneg hy7 hy11, mul_nonneg hy10 hbr9n,
            mul_nonneg hy12 hbr10n, mul_nonneg hbr8n hbr10n]
        · have hbr10n : (0 : ℝ) ≤ y1 - (0) := by linarith
          rcases le_total y2 (1 / 2 : ℝ) with hbr11 | hbr11
          · have hbr11n : (0 : ℝ) ≤ 1 / 2 - y2 := by linarith
            linarith [mul_nonneg hx0 hx7, mul_nonneg hx0 hy11, mul_nonneg hx4 hy4,
              mul_nonneg hx5 hx12, mul_nonneg hx5 hy9, mul_nonneg hx6 hx13, mul_nonneg hx6 hbr10n,
              mul_nonneg hx6 hbr11n, mul_nonneg hx7 hy7, mul_nonneg hx11 hy11, mul_nonneg hx12 hy2,
              mul_nonneg hx12 hy12, mul_nonneg hx12 hbr8n, mul_nonneg hx12 hbr10n,
              mul_nonneg hx13 hy11, mul_nonneg hx13 hbr9n, mul_nonneg hy4 hy13,
              mul_nonneg hy4 hbr0n, mul_nonneg hy4 hbr8n, mul_nonneg hy6 hy9, mul_nonneg hy7 hy11,
              mul_nonneg hy9 hbr8n, mul_nonneg hy9 hbr10n, mul_nonneg hy9 hbr11n,
              mul_nonneg hy11 hbr0n, mul_nonneg hbr9n hbr11n]
          · have hbr11n : (0 : ℝ) ≤ y2 - (1 / 2) := by linarith
            linarith [mul_nonneg hx0 hx7, mul_nonneg hx5 hx12, mul_nonneg hx5 hy4,
              mul_nonneg hx6 hx13, mul_nonneg hx6 hy10, mul_nonneg hx7 hy5, mul_nonneg hx7 hy7,
              mul_nonneg hx7 hbr8n, mul_nonneg hx7 hbr9n, mul_nonneg hx11 hy11,
              mul_nonneg hx12 hy10, mul_nonneg hx13 hy11, mul_nonneg hx13 hbr9n,
              mul_nonneg hx13 hbr11n, mul_nonneg hy4 hy7, mul_nonneg hy4 hy12,
              mul_nonneg hy4 hbr8n, mul_nonneg hy4 hbr10n, mul_nonneg hy5 hy10,
              mul_nonneg hy6 hy11, mul_nonneg hy7 hy11, mul_nonneg hy9 hy10, mul_nonneg hy9 hbr8n,
              mul_nonneg hy10 hbr11n, mul_nonneg hy11 hbr8n]
      · have hbr9n : (0 : ℝ) ≤ x2 - (0) := by linarith
        linarith [mul_nonneg hx0 hy11, mul_nonneg hx4 hx12, mul_nonneg hx4 hy4,
          mul_nonneg hx5 hx12, mul_nonneg hx6 hx13, mul_nonneg hx6 hy6, mul_nonneg hx6 hbr8n,
          mul_nonneg hx7 hx10, mul_nonneg hx7 hx11, mul_nonneg hx7 hy5, mul_nonneg hx7 hy7,
          mul_nonneg hx7 hbr0n, mul_nonneg hx10 hbr9n, mul_nonneg hx11 hy11, mul_nonneg hx12 hy10,
          mul_nonneg hx12 hy11, mul_nonneg hx12 hy12, mul_nonneg hy4 hy13, mul_nonneg hy4 hbr0n,
          mul_nonneg hy5 hy11, mul_nonneg hy5 hbr9n, mul_nonneg hy6 hy9, mul_nonneg hy9 hbr8n,
          mul_nonneg hy11 hbr0n, mul_nonneg hbr0n hbr9n]
    · have hbr8n : (0 : ℝ) ≤ x1 - (0) := by linarith
      rcases le_total y1 (0 : ℝ) with hbr12 | hbr12
      · have hbr12n : (0 : ℝ) ≤ 0 - y1 := by linarith
        rcases le_total x2 (0 : ℝ) with hbr13 | hbr13
        · have hbr13n : (0 : ℝ) ≤ 0 - x2 := by linarith
          rcases le_total y2 (1 / 2 : ℝ) with hbr14 | hbr14
          · have hbr14n : (0 : ℝ) ≤ 1 / 2 - y2 := by linarith
            linarith [mul_nonneg hx5 hx11, mul_nonneg hx5 hy7, mul_nonneg hx5 hbr0n,
              mul_nonneg hx6 hy6, mul_nonneg hx7 hx9, mul_nonneg hx7 hx11, mul_nonneg hx7 hy7,
              mul_nonneg hx7 hbr0n, mul_nonneg hx9 hy0, mul_nonneg hx9 hy11, mul_nonneg hx9 hbr8n,
              mul_nonneg hx9 hbr12n, mul_nonneg hx9 hbr14n, mul_nonneg hx11 hy12,
              mul_nonneg hx12 hy12, mul_nonneg hx13 hbr0n, mul_nonneg hx13 hbr8n,
              mul_nonneg hx13 hbr13n, mul_nonneg hy4 hy12, mul_nonneg hy5 hy12,
              mul_nonneg hy6 hy11, mul_nonneg hy6 hbr12n, mul_nonneg hy7 hbr14n,
              mul_nonneg hbr0n hbr14n]
          · have hbr14n : (0 : ℝ) ≤ y2 - (1 / 2) := by linarith
            linarith [mul_nonneg hx0 hx5, mul_nonneg hx0 hy10, mul_nonneg hx4 hx13,
              mul_nonneg hx4 hy10, mul_nonneg hx5 hy5, mul_nonneg hx5 hbr13n, mul_nonneg hx6 hx13,
              mul_nonneg hx7 hx11, mul_nonneg hx7 hy6, mul_nonneg hx7 hbr14n, mul_nonneg hx9 hy10,
              mul_nonneg hx9 hbr8n, mul_nonneg hx12 hy12, mul_nonneg hx13 hy0,
              mul_nonneg hx13 hy11, mul_nonneg hx13 hy13, mul_nonneg hy6 hy11,
              mul_nonneg hy6 hbr8n, mul_nonneg hy7 hy10, mul_nonneg hy10 hbr13n,
              mul_nonneg hy10 hbr14n, mul_nonneg hy11 hbr14n, mul_nonneg hy12 hbr8n,
              mul_nonneg hy12 hbr12n, mul_nonneg hy12 hbr14n]
        · have hbr13n : (0 : ℝ) ≤ x2 - (0) := by linarith
          linarith [mul_nonneg hx4 hy0, mul_nonneg hx4 hy4, mul_nonneg hx4 hbr12n,
            mul_nonneg hx4 hbr13n, mul_nonneg hx5 hx11, mul_nonneg hx5 hbr0n, mul_nonneg hx6 hx9,
            mul_nonneg hx6 hy6, mul_nonneg hx7 hbr0n, mul_nonneg hx9 hbr12n, mul_nonneg hx10 hy6,
            mul_nonneg hx10 hy12, mul_nonneg hx11 hy0, mul_nonneg hx11 hy11, mul_nonneg hx12 hy12,
            mul_nonneg hy0 hy6, mul_nonneg hy4 hy12, mul_nonneg hy5 hy12, mul_nonneg hy6 hy13,
            mul_nonneg hy6 hbr12n, mul_nonneg hy7 hy11, mul_nonneg hy7 hbr12n,
            mul_nonneg hy7 hbr13n, mul_nonneg hy10 hbr0n]
      · have hbr12n : (0 : ℝ) ≤ y1 - (0) := by linarith
        linarith [mul_nonneg hx0 hx7, mul_nonneg hx0 hy4, mul_nonneg hx2 hx5, mul_nonneg hx4 hx13,
          mul_nonneg hx4 hy10, mul_nonneg hx5 hx10, mul_nonneg hx5 hy5, mul_nonneg hx5 hbr0n,
          mul_nonneg hx6 hx13, mul_nonneg hx6 hy10, mul_nonneg hx7 hx11, mul_nonneg hx9 hbr8n,
          mul_nonneg hx10 hy10, mul_nonneg hx11 hy11, mul_nonneg hx13 hbr0n, mul_nonneg hy4 hbr12n,
          mul_nonneg hy5 hy10, mul_nonneg hy6 hy11, mul_nonneg hy7 hbr8n, mul_nonneg hy12 hbr8n,
          mul_nonneg hbr8n hbr12n]

set_option maxHeartbeats 1600000 in
-- the branch-and-certify case tree is large
@[category API, AMS 52]
theorem certC12 (x0 x1 x2 y0 y1 y2 : ℝ)
    (hx0 : (0 : ℝ) ≤ 3 / 2 - (x0 + x1 + x2)) (hx1 : (0 : ℝ) ≤ 3 / 2 - (x0 + x1 - x2))
    (hx2 : (0 : ℝ) ≤ 3 / 2 - (x0 - x1 + x2)) (hx3 : (0 : ℝ) ≤ 3 / 2 - (x0 - x1 - x2))
    (hx4 : (0 : ℝ) ≤ 3 / 2 - (-x0 + x1 + x2)) (hx5 : (0 : ℝ) ≤ 3 / 2 - (-x0 + x1 - x2))
    (hx6 : (0 : ℝ) ≤ 3 / 2 - (-x0 - x1 + x2)) (hx7 : (0 : ℝ) ≤ 3 / 2 - (-x0 - x1 - x2))
    (hx8 : (0 : ℝ) ≤ 13 / 15 - x0) (hx9 : (0 : ℝ) ≤ 13 / 15 - x1)
    (hx10 : (0 : ℝ) ≤ 13 / 15 - x2) (hx11 : (0 : ℝ) ≤ 5 / 12 - (x0 + x1 + x2))
    (hx12 : (0 : ℝ) ≤ x1 - x0) (hx13 : (0 : ℝ) ≤ x2 - x0)
    (hy0 : (0 : ℝ) ≤ 3 / 2 - (y0 + y1 + y2)) (hy1 : (0 : ℝ) ≤ 3 / 2 - (y0 + y1 - y2))
    (hy2 : (0 : ℝ) ≤ 3 / 2 - (y0 - y1 + y2)) (hy3 : (0 : ℝ) ≤ 3 / 2 - (y0 - y1 - y2))
    (hy4 : (0 : ℝ) ≤ 3 / 2 - (-y0 + y1 + y2)) (hy5 : (0 : ℝ) ≤ 3 / 2 - (-y0 + y1 - y2))
    (hy6 : (0 : ℝ) ≤ 3 / 2 - (-y0 - y1 + y2)) (hy7 : (0 : ℝ) ≤ 3 / 2 - (-y0 - y1 - y2))
    (hy8 : (0 : ℝ) ≤ 13 / 15 - y0) (hy9 : (0 : ℝ) ≤ 13 / 15 - y1)
    (hy10 : (0 : ℝ) ≤ 13 / 15 - y2) (hy11 : (0 : ℝ) ≤ -(7 / 24) - y0)
    (hy12 : (0 : ℝ) ≤ y1 - y0) (hy13 : (0 : ℝ) ≤ y2 - y0)
    :
    (x0 - y0) ^ 2 + (x1 - y1) ^ 2 + (x2 - y2) ^ 2 ≤ 149 / 50 := by
  rcases le_total y1 (0 : ℝ) with hbr0 | hbr0
  · have hbr0n : (0 : ℝ) ≤ 0 - y1 := by linarith
    rcases le_total x2 (0 : ℝ) with hbr1 | hbr1
    · have hbr1n : (0 : ℝ) ≤ 0 - x2 := by linarith
      rcases le_total y2 (0 : ℝ) with hbr2 | hbr2
      · have hbr2n : (0 : ℝ) ≤ 0 - y2 := by linarith
        linarith [mul_nonneg hx4 hx13, mul_nonneg hx4 hy6, mul_nonneg hx5 hx11,
          mul_nonneg hx5 hx13, mul_nonneg hx5 hy7, mul_nonneg hx5 hbr1n, mul_nonneg hx6 hx9,
          mul_nonneg hx6 hx13, mul_nonneg hx6 hy6, mul_nonneg hx6 hbr2n, mul_nonneg hx7 hx9,
          mul_nonneg hx7 hx11, mul_nonneg hx7 hy7, mul_nonneg hx9 hx12, mul_nonneg hx9 hbr0n,
          mul_nonneg hx12 hy12, mul_nonneg hx13 hy12, mul_nonneg hy5 hy12, mul_nonneg hy6 hy13,
          mul_nonneg hy6 hbr1n, mul_nonneg hy7 hbr0n, mul_nonneg hy7 hbr2n, mul_nonneg hy12 hbr1n]
      · have hbr2n : (0 : ℝ) ≤ y2 - (0) := by linarith
        rcases le_total x1 (0 : ℝ) with hbr3 | hbr3
        · have hbr3n : (0 : ℝ) ≤ 0 - x1 := by linarith
          linarith [mul_nonneg hx2 hy10, mul_nonneg hx4 hx13, mul_nonneg hx4 hy10,
            mul_nonneg hx5 hx12, mul_nonneg hx5 hy5, mul_nonneg hx5 hbr0n, mul_nonneg hx6 hx13,
            mul_nonneg hx6 hbr3n, mul_nonneg hx7 hx11, mul_nonneg hx7 hy6, mul_nonneg hx7 hy7,
            mul_nonneg hx12 hy11, mul_nonneg hx12 hy12, mul_nonneg hx13 hy11, mul_nonneg hx13 hy13,
            mul_nonneg hx13 hbr0n, mul_nonneg hx13 hbr1n, mul_nonneg hy1 hbr3n,
            mul_nonneg hy5 hy10, mul_nonneg hy5 hbr3n, mul_nonneg hy6 hy11, mul_nonneg hy7 hy10,
            mul_nonneg hy7 hy11, mul_nonneg hy10 hbr1n, mul_nonneg hy10 hbr2n,
            mul_nonneg hy12 hbr0n]
        · have hbr3n : (0 : ℝ) ≤ x1 - (0) := by linarith
          rcases le_total y2 (1 / 2 : ℝ) with hbr4 | hbr4
          · have hbr4n : (0 : ℝ) ≤ 1 / 2 - y2 := by linarith
            linarith [mul_nonneg hx4 hx13, mul_nonneg hx5 hx11, mul_nonneg hx5 hy7,
              mul_nonneg hx6 hx9, mul_nonneg hx6 hx13, mul_nonneg hx6 hy6, mul_nonneg hx7 hy7,
              mul_nonneg hx9 hy4, mul_nonneg hx9 hbr0n, mul_nonneg hx9 hbr3n, mul_nonneg hx9 hbr4n,
              mul_nonneg hx11 hy11, mul_nonneg hx11 hy12, mul_nonneg hx11 hbr4n,
              mul_nonneg hx12 hy12, mul_nonneg hx13 hy12, mul_nonneg hx13 hy13,
              mul_nonneg hx13 hbr2n, mul_nonneg hy4 hy12, mul_nonneg hy5 hy12, mul_nonneg hy6 hy13,
              mul_nonneg hy6 hbr0n, mul_nonneg hy6 hbr1n, mul_nonneg hy7 hy11,
              mul_nonneg hy7 hbr4n]
          · have hbr4n : (0 : ℝ) ≤ y2 - (1 / 2) := by linarith
            linarith [mul_nonneg hx2 hx5, mul_nonneg hx4 hx13, mul_nonneg hx5 hy5,
              mul_nonneg hx5 hbr0n, mul_nonneg hx6 hx13, mul_nonneg hx7 hx11, mul_nonneg hx7 hy6,
              mul_nonneg hx7 hbr4n, mul_nonneg hx9 hbr3n, mul_nonneg hx11 hy10,
              mul_nonneg hx12 hy12, mul_nonneg hx13 hy11, mul_nonneg hx13 hy13,
              mul_nonneg hx13 hbr0n, mul_nonneg hx13 hbr4n, mul_nonneg hy1 hy12,
              mul_nonneg hy5 hy12, mul_nonneg hy6 hy11, mul_nonneg hy6 hbr3n, mul_nonneg hy7 hy10,
              mul_nonneg hy7 hy11, mul_nonneg hy10 hbr1n, mul_nonneg hy10 hbr4n,
              mul_nonneg hy12 hbr0n, mul_nonneg hy12 hbr3n, mul_nonneg hy12 hbr4n]
    · have hbr1n : (0 : ℝ) ≤ x2 - (0) := by linarith
      rcases le_total x1 (0 : ℝ) with hbr5 | hbr5
      · have hbr5n : (0 : ℝ) ≤ 0 - x1 := by linarith
        rcases le_total y2 (0 : ℝ) with hbr6 | hbr6
        · have hbr6n : (0 : ℝ) ≤ 0 - y2 := by linarith
          linarith [mul_nonneg hx4 hx12, mul_nonneg hx4 hy5, mul_nonneg hx5 hx12,
            mul_nonneg hx5 hy5, mul_nonneg hx6 hx11, mul_nonneg hx6 hy7, mul_nonneg hx7 hy7,
            mul_nonneg hx10 hy4, mul_nonneg hx10 hy10, mul_nonneg hx10 hbr1n,
            mul_nonneg hx10 hbr6n, mul_nonneg hx11 hy11, mul_nonneg hx11 hy13,
            mul_nonneg hx12 hy13, mul_nonneg hx13 hy13, mul_nonneg hy0 hy7, mul_nonneg hy5 hy12,
            mul_nonneg hy5 hbr5n, mul_nonneg hy6 hy13, mul_nonneg hy7 hbr0n, mul_nonneg hy7 hbr6n,
            mul_nonneg hy12 hbr0n, mul_nonneg hbr0n hbr5n]
        · have hbr6n : (0 : ℝ) ≤ y2 - (0) := by linarith
          linarith [mul_nonneg hx4 hx12, mul_nonneg hx4 hy4, mul_nonneg hx4 hbr0n,
            mul_nonneg hx5 hbr6n, mul_nonneg hx6 hx12, mul_nonneg hx6 hy6, mul_nonneg hx6 hbr5n,
            mul_nonneg hx7 hx11, mul_nonneg hx7 hy7, mul_nonneg hx7 hbr6n, mul_nonneg hx10 hx13,
            mul_nonneg hx10 hbr1n, mul_nonneg hx10 hbr5n, mul_nonneg hx11 hy10,
            mul_nonneg hx11 hbr1n, mul_nonneg hx12 hy11, mul_nonneg hx12 hy12, mul_nonneg hy5 hy10,
            mul_nonneg hy5 hbr1n, mul_nonneg hy6 hy11, mul_nonneg hy7 hy10, mul_nonneg hy7 hy11,
            mul_nonneg hy10 hbr6n, mul_nonneg hy12 hbr0n, mul_nonneg hbr1n hbr6n]
      · have hbr5n : (0 : ℝ) ≤ x1 - (0) := by linarith
        linarith [mul_nonneg hx4 hx12, mul_nonneg hx4 hx13, mul_nonneg hx4 hy4, mul_nonneg hx5 hy5,
          mul_nonneg hx5 hy7, mul_nonneg hx6 hy6, mul_nonneg hx7 hx11, mul_nonneg hx7 hy7,
          mul_nonneg hx9 hbr0n, mul_nonneg hx10 hy6, mul_nonneg hx10 hbr1n, mul_nonneg hx11 hy11,
          mul_nonneg hx11 hbr1n, mul_nonneg hx11 hbr5n, mul_nonneg hx12 hy12, mul_nonneg hx13 hy13,
          mul_nonneg hy5 hbr1n, mul_nonneg hy6 hy13, mul_nonneg hy7 hy10, mul_nonneg hy7 hy11,
          mul_nonneg hy7 hbr1n, mul_nonneg hy12 hbr0n, mul_nonneg hy12 hbr5n,
          mul_nonneg hy13 hbr1n, mul_nonneg hbr1n hbr5n]
  · have hbr0n : (0 : ℝ) ≤ y1 - (0) := by linarith
    rcases le_total x2 (0 : ℝ) with hbr7 | hbr7
    · have hbr7n : (0 : ℝ) ≤ 0 - x2 := by linarith
      rcases le_total x1 (0 : ℝ) with hbr8 | hbr8
      · have hbr8n : (0 : ℝ) ≤ 0 - x1 := by linarith
        rcases le_total y2 (0 : ℝ) with hbr9 | hbr9
        · have hbr9n : (0 : ℝ) ≤ 0 - y2 := by linarith
          linarith [mul_nonneg hx1 hy9, mul_nonneg hx4 hx12, mul_nonneg hx5 hx12,
            mul_nonneg hx5 hy9, mul_nonneg hx6 hx13, mul_nonneg hx6 hy4, mul_nonneg hx6 hy6,
            mul_nonneg hx6 hbr8n, mul_nonneg hx6 hbr9n, mul_nonneg hx7 hx11, mul_nonneg hx7 hy7,
            mul_nonneg hx11 hy11, mul_nonneg hx12 hy11, mul_nonneg hx12 hy12,
            mul_nonneg hx12 hbr9n, mul_nonneg hx13 hy13, mul_nonneg hx13 hbr7n,
            mul_nonneg hy0 hbr7n, mul_nonneg hy2 hbr7n, mul_nonneg hy5 hy11, mul_nonneg hy6 hy9,
            mul_nonneg hy6 hbr7n, mul_nonneg hy7 hy9, mul_nonneg hy9 hbr8n, mul_nonneg hy13 hbr9n]
        · have hbr9n : (0 : ℝ) ≤ y2 - (0) := by linarith
          rcases le_total y2 (1 / 2 : ℝ) with hbr10 | hbr10
          · have hbr10n : (0 : ℝ) ≤ 1 / 2 - y2 := by linarith
            linarith [mul_nonneg hx5 hx12, mul_nonneg hx6 hx13, mul_nonneg hx6 hy6,
              mul_nonneg hx6 hbr0n, mul_nonneg hx6 hbr10n, mul_nonneg hx7 hx11, mul_nonneg hx7 hy4,
              mul_nonneg hx7 hy5, mul_nonneg hx7 hy7, mul_nonneg hx7 hbr7n, mul_nonneg hx9 hy4,
              mul_nonneg hx11 hy11, mul_nonneg hx12 hy11, mul_nonneg hx12 hy12,
              mul_nonneg hx12 hbr8n, mul_nonneg hx12 hbr10n, mul_nonneg hx13 hy11,
              mul_nonneg hy4 hy7, mul_nonneg hy4 hy13, mul_nonneg hy4 hbr9n, mul_nonneg hy5 hy11,
              mul_nonneg hy6 hy9, mul_nonneg hy7 hy11, mul_nonneg hy9 hbr8n, mul_nonneg hy9 hbr10n,
              mul_nonneg hbr7n hbr10n]
          · have hbr10n : (0 : ℝ) ≤ y2 - (1 / 2) := by linarith
            linarith [mul_nonneg hx4 hx7, mul_nonneg hx5 hx12, mul_nonneg hx5 hy4,
              mul_nonneg hx6 hx13, mul_nonneg hx7 hx11, mul_nonneg hx7 hy5, mul_nonneg hx7 hy7,
              mul_nonneg hx8 hy11, mul_nonneg hx9 hy4, mul_nonneg hx11 hy11, mul_nonneg hx12 hy10,
              mul_nonneg hx12 hy11, mul_nonneg hx13 hy11, mul_nonneg hx13 hbr10n,
              mul_nonneg hy4 hy6, mul_nonneg hy4 hy12, mul_nonneg hy4 hbr8n, mul_nonneg hy5 hy10,
              mul_nonneg hy6 hy11, mul_nonneg hy9 hbr8n, mul_nonneg hy10 hbr7n,
              mul_nonneg hy10 hbr9n, mul_nonneg hy10 hbr10n]
      · have hbr8n : (0 : ℝ) ≤ x1 - (0) := by linarith
        linarith [mul_nonneg hx4 hx13, mul_nonneg hx4 hy4, mul_nonneg hx4 hy10,
          mul_nonneg hx5 hx12, mul_nonneg hx5 hy5, mul_nonneg hx6 hx13, mul_nonneg hx7 hx11,
          mul_nonneg hx7 hy7, mul_nonneg hx7 hbr0n, mul_nonneg hx9 hbr8n, mul_nonneg hx11 hy11,
          mul_nonneg hx13 hy9, mul_nonneg hx13 hy11, mul_nonneg hx13 hy13, mul_nonneg hx13 hbr7n,
          mul_nonneg hy1 hy10, mul_nonneg hy4 hbr0n, mul_nonneg hy5 hy10, mul_nonneg hy6 hy11,
          mul_nonneg hy6 hbr8n, mul_nonneg hy7 hy11, mul_nonneg hy9 hy10, mul_nonneg hy10 hy13,
          mul_nonneg hy10 hbr7n, mul_nonneg hy12 hbr8n, mul_nonneg hbr0n hbr8n]
    · have hbr7n : (0 : ℝ) ≤ x2 - (0) := by linarith
      rcases le_total x0 (-1 / 2 : ℝ) with hbr11 | hbr11
      · have hbr11n : (0 : ℝ) ≤ -1 / 2 - x0 := by linarith
        rcases le_total y2 (0 : ℝ) with hbr12 | hbr12
        · have hbr12n : (0 : ℝ) ≤ 0 - y2 := by linarith
          linarith [mul_nonneg hx4 hx12, mul_nonneg hx4 hy9, mul_nonneg hx5 hy5,
            mul_nonneg hx6 hx9, mul_nonneg hx6 hy6, mul_nonneg hx7 hy5, mul_nonneg hx7 hy7,
            mul_nonneg hx7 hbr11n, mul_nonneg hx10 hy9, mul_nonneg hx10 hbr7n, mul_nonneg hx11 hy9,
            mul_nonneg hx12 hy13, mul_nonneg hx12 hbr0n, mul_nonneg hy5 hy11, mul_nonneg hy5 hbr7n,
            mul_nonneg hy6 hy9, mul_nonneg hy7 hy9, mul_nonneg hy7 hy11, mul_nonneg hy7 hbr7n,
            mul_nonneg hy9 hbr0n, mul_nonneg hy11 hbr11n, mul_nonneg hy13 hbr7n,
            mul_nonneg hy13 hbr12n, mul_nonneg hbr11n hbr12n]
        · have hbr12n : (0 : ℝ) ≤ y2 - (0) := by linarith
          linarith [mul_nonneg hx4 hx12, mul_nonneg hx4 hy9, mul_nonneg hx5 hx12,
            mul_nonneg hx6 hx9, mul_nonneg hx6 hx13, mul_nonneg hx6 hy6, mul_nonneg hx6 hbr0n,
            mul_nonneg hx6 hbr7n, mul_nonneg hx7 hx11, mul_nonneg hx7 hbr0n, mul_nonneg hx7 hbr12n,
            mul_nonneg hx11 hy4, mul_nonneg hx11 hy11, mul_nonneg hx12 hy11, mul_nonneg hx12 hy12,
            mul_nonneg hx12 hbr0n, mul_nonneg hy4 hbr12n, mul_nonneg hy5 hy11,
            mul_nonneg hy5 hbr7n, mul_nonneg hy6 hy9, mul_nonneg hy11 hbr11n,
            mul_nonneg hy13 hbr7n, mul_nonneg hbr7n hbr12n]
      · have hbr11n : (0 : ℝ) ≤ x0 - (-1 / 2) := by linarith
        rcases le_total x1 (0 : ℝ) with hbr13 | hbr13
        · have hbr13n : (0 : ℝ) ≤ 0 - x1 := by linarith
          linarith [mul_nonneg hx6 hx13, mul_nonneg hx6 hbr0n, mul_nonneg hx6 hbr13n,
            mul_nonneg hx10 hy4, mul_nonneg hx10 hy9, mul_nonneg hx10 hbr7n, mul_nonneg hx11 hx12,
            mul_nonneg hx11 hy9, mul_nonneg hx11 hy11, mul_nonneg hx11 hbr11n, mul_nonneg hx12 hy7,
            mul_nonneg hx12 hy12, mul_nonneg hx12 hy13, mul_nonneg hx12 hbr0n,
            mul_nonneg hx12 hbr11n, mul_nonneg hx12 hbr13n, mul_nonneg hx13 hy13,
            mul_nonneg hy4 hy5, mul_nonneg hy4 hy13, mul_nonneg hy5 hy11, mul_nonneg hy5 hbr7n,
            mul_nonneg hy5 hbr11n, mul_nonneg hy6 hy13, mul_nonneg hy7 hbr11n,
            mul_nonneg hy9 hbr0n, mul_nonneg hy13 hbr13n]
        · have hbr13n : (0 : ℝ) ≤ x1 - (0) := by linarith
          linarith [mul_nonneg hx9 hy5, mul_nonneg hx10 hx13, mul_nonneg hx10 hy4,
            mul_nonneg hx10 hy6, mul_nonneg hx11 hx13, mul_nonneg hx11 hy10, mul_nonneg hx11 hy11,
            mul_nonneg hx11 hbr7n, mul_nonneg hx11 hbr13n, mul_nonneg hx12 hy11,
            mul_nonneg hx12 hy13, mul_nonneg hx12 hbr11n, mul_nonneg hx13 hy13,
            mul_nonneg hx13 hbr13n, mul_nonneg hy4 hy13, mul_nonneg hy4 hbr11n,
            mul_nonneg hy5 hy10, mul_nonneg hy5 hbr7n, mul_nonneg hy5 hbr11n, mul_nonneg hy7 hy11,
            mul_nonneg hy7 hbr7n, mul_nonneg hy7 hbr11n, mul_nonneg hy9 hbr0n,
            mul_nonneg hbr0n hbr13n, mul_nonneg hbr7n hbr13n]
end Space.Cert

end Borsuk
