name: Notify erdosproblems of update

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository dispatch event
        uses: peter-evans/repository-dispatch@v3
        with:
          # A PAT with 'repo' scope is needed to trigger a workflow in
          token: ${{ secrets.REPO_DISPATCH_PAT }}
          repository: mo271/erdosproblems
          event-type: formal-conjecture-updated
